# ROS Kinect
kinect:
  # build: ros-kinect/.
  image: toddsampson/ros-indigo-kinect
  container_name: kinect
  hostname: kinect
  net: rosdocker
  devices:
      - "/dev/bus/usb:/dev/bus/usb"
  environment:
      - "ROS_HOSTNAME=kinect"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  # command: bash
  command: roslaunch freenect_launch freenect.launch depth_registration:=true


# ROS Image View
image_view:
  # build: ros-image_pipeline/.
  image: toddsampson/ros-indigo-image_pipeline
  container_name: image_view
  hostname: image_view
  volumes_from:
      - "rosmaster"
  net: rosdocker
  volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
  environment:
      - "DISPLAY=$DISPLAY"
      - "ROS_HOSTNAME=image_view"
      - "ROS_MASTER_URI=http://rosmaster:11311"
  command: rosrun image_view image_view image:=/camera/depth_registered/image 
  
  # command: rosrun image_view image_view image:=/image_raw



# ROS MASTER (ROSCORE)
rosmaster:
  image: ros:latest
  container_name: rosmaster
  hostname: rosmaster
  net: rosdocker
  ports:
       - "11311:11311"
  command: roscore
